### PR TITLE
Increase SPI MCLK configuration speed

### PR DESCRIPTION
**Pull request by gregdavill**
I noticed the probe takes a little while to boot-up. As it's operating on SPI mode, with a default slow MCLK speed.
Even with bitstream compression, since you need to load 2 bitstreams, (bootloader, then main) it's quick but still takes a noticeable amount of time.

We can pass an argument to ecppack to set the MCLK speed to 62MHz, which reduces config time down to a few ms.

I notice you're also not making use of fast-read/dual-read or qspi modes, which would also speed up the configuration, The settings are there but commented out, were you seeing issues when using qspi modes? 
Or does the FLASH you use not have the Quad-Enable non-volatile option set from the factory?

This currently just tacks the `--freq` option into the bootaddr value. Once this LiteX PR is merged it can have a dedicated parameter: https://github.com/enjoy-digital/litex/pull/1352

### CODE REVIEW

**Comment by zyp** [comment]
> I notice you're also not making use of fast-read/dual-read or qspi modes, which would also speed up the configuration, The settings are there but commented out, were you seeing issues when using qspi modes?

Yes, I tested it, but couldn't get it to work. The FPGA refused to load the gateware if I set the spimode at all, i.e. neither fast-read nor qspi worked. More testing on this is welcome. The `QUAD_NV` bit in the flash is set by the [Orbtrace testsuite](https://github.com/orbcode/orbtrace_testsuite/blob/main/bin/enable-flash-qspi.py), so that's not the issue.

For the `--freq` option, I'm inclined to wait for your LiteX PR to get merged first.

**Comment by gregdavill** [comment]
Okay, I'll take a look and see if there are any issues I spot. 

Sure thing, that makes sense, 
I suspect it will be merged soon, I'll update the LiteX dep and make use of the new parameters when that happens.

**Comment by mubes** [comment]
Ah...it's slightly deliberate in a way that we haven't documented :-)

Before booting the LED controller outputs the state of all of the voltage
levels on the probe (they're marked on the PCB). The slow start is to give
us time to see them before normal operation starts.

It's very useful for initial test but at that time there's no programming
in the probes anyway so the LEDs stay in their power reporting mode, so
perhaps we should speed it up (or at least speed up the application load,
if not the bootstrap one).

**Comment by zyp** [comment]
I'd argue it doesn't have to be deliberately slowed down, the voltage rail information is only useful to give extra diagnostic if the FPGA doesn't boot, since it won't if either of the rails are missing.

The main reason we're not already increasing the frequency is that the `--freq` parameter is not exposed through LiteX yet.

**Comment by mubes** [comment]
That's true. I don't know if compression is on in the production builds too
now...the combination of the two would make things largely instantaneous.

**Comment by gregdavill** [comment]
The trellis backend changes have been added to LiteX now. Updated the PR.

**Comment by gregdavill** [comment]
Support in LiteX is working now. Does this look good to you?

**Comment by zyp** [comment]
Thanks!

**Pull request merged**
